version: "3.7"

# Cria redes
networks:
  app-lan:
    driver: bridge
  db-lan:
    driver: bridge
  
# Cria servicos
services:

  # Servidor web
  webserver:
    image: nginx:1.23.4
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-lan
    depends_on:
      - app
  
  # Servidor de aplicação
  app:
    build:
      args:
        user: weydans
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: app
    image: php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-lan
      - db-lan