version: "3.7"

# Cria redes
networks:
  app-lan:
    driver: bridge
  db-lan:
    driver: bridge
  
# Cria servicos
services:

  # Servidor web
  webserver:
    image: nginx:1.23.4
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - app-lan
    depends_on:
      - app
  
  # Servidor de aplicação
  app:
    build:
      args:
        user: weydans
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    container_name: app
    image: php-fpm
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-lan
      - db-lan
    depends_on:
      - db

  # Servidor de banco de dados
  db:
    image: mysql:5.7.42
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - ./.data:/var/lib/mysql
    networks:
      - db-lan
  
  # Servidor de documentação com Swagger
  doc:
    image: swaggerapi/swagger-ui
    container_name: doc
    restart: unless-stopped
    environment:
      SWAGGER_JSON: /api/v0/swagger.json
    ports:
      - 8081:8080
    volumes:
      - ./docker/doc/swagger.json:/api/v0/swagger.json

