version: "3.7"

# Cria redes
networks:
  app-lan:
    driver: bridge
  db-lan:
    driver: bridge
  
# Cria servicos
services:

  # Servidor web
  webserver:
    image: nginx:1.23.4
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - app-lan